theme = "dream"
baseURL = 'https://wthnote.netlify.app/'
defaultContentLanguage = "en"
languageCode = "en"
title = 'WTH'


[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 1


[params]
  favicon = "favicon.ico"
  author = "ftdr"
  headerTitle = "WTH"
  avatar = "img/avatar.png"
